name: CI

on: [pull_request]

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Check coding standards
        run: yarn run format:check
      - name: Make static analysis (eslint)
        run: yarn run eslint:check
      - name: Make static analysis (typescript)
        run: yarn run typescript:check
